import { Schema, model } from "mongoose";


const ProductData = new Schema(
    {
        ProductName:{type: String,required: true},
        FrontImage: {type: Object,required: true},
        BackImage: {type: Object,required: true},
        ProductSize: [],
        ColorVariant:{type:Number, required:true},
        SizeVariant:{type:Number, required:true},
        ProductPrice:{type: Number,required: true},
        PreviousPrice:{type: Number,required: true},
        ProductMainHeading:{type: String,required: true},
        DescountPriceInPercent:{type: Number,required: true},
        TotalSoldAmount:{type:Number},
        TodaySoldAmount:{type:Number},
        TodayTargetSaleAmount:{type:Number},
        TotalTargetSaleAmount: {type: Number,required: true},
        TotalSoldQuentity:{type:Number},
        TodaySoldQuentity:{type:Number},
        TodayTargetQuentity:{type:Number},
        TotalTargetQuentity:{type:Number},
        TodayReturn:{type:Number},
        TotalReturn:{type:Number},
        InStockQuentity: {type:Number,required:true},
        InStockAvailableQuentity: {type:Number},
        StartDate: {type: Date,required: true},
        EndDate: {type: Date,required: true},
        ProductVideos: [{videoUrl:{type:String},CloudinaryPublicId:{type:String},fileType:{type:String}}],
        ProductPhotos: [{photoUrl:{type:String},CloudinaryPublicId:{type:String},fileType:{type:String},backgroundType:{type:String}}],
        ProductFutures: [{key:{type:String},value:{type:String}}],
        ProductSpecification: [{spcKey:{type:String},spcValue:{type:String}}],
        ProductDescription: [{heading:{type:String},descripTion:{type:String},photoUrl:{type:String},CloudinaryPublicId:{type:String},fileType:{type:String}}],
        ProductColors: [{colorName:{type:String},colorImage:{type:String},CloudinaryPublicId:{type:String},fileType:{type:String}}],
        ProductShortDescription:{
            productShortHeading:{type:String},
            productShortDescVariations:[{key:{type:String},value:{type:String}}],
            productShortDescKeyAttributes:[{key:{type:String},value:{type:String}}],
            productShortDescOtherAttributes:[{key:{type:String},value:{type:String}}],
        },
        CustomerReviews: [{type: Schema.Types.ObjectId,ref: 'Review'}],
        InStock: {type:Boolean,default:true},
        IsPublic: {type:Boolean,default:false},
        TodayTotaladCost:{type:Number},
        TodayadCostPerSale:{type:Number},
        TotalAdCostPerSale:{type:Number},
        TotalAdCost:{type:Number},
        TodayOtherCost:{type:Number},
        TodayOtherCostPerSale:{type:Number},
        TotalOtherCostPerSale:{type:Number},
        TotalOtherCost:{type:Number},
        TodayDelibaryCost:{type:Number},
        TodayDelibaryCostPersale:{type:Number},
        TotalDelibaryCostPersale:{type:Number},
        TotalDelibaryCost:{type:Number},
        TodayTotalProfit:{type:Number},
        TodayProfitPerSale:{type:Number},
        TotalProfitPerSale:{type:Number},
        TotalProfit:{type:Number},
        TodayTargetProfit:{type:Number},
        TotalTargetProfit:{type:Number},
        TotalPackgingCost:{type:Number},
        PackgingCostPerProduct:{type:Number},
        TotalPrductBuyingCost:{type:Number},
        BuyingCostPerProduct:{type:Number},
        TotalShippingCost:{type:Number},
        ShippingCostPerProduct:{type:Number},
        TotalProcessingCost:{type:Number}
    },
    { timestamps: true}
);

export default model("ProductsData", ProductData, "currentProducts")
