export const productArray = [
    {
      id:1,
      discount: "40%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
      altText: "T-shirt",
      priceBeforeDiscount: "4kd",
      priceAfterDiscount: "2kd",
      productName: "Boys T-shirt",
      availableColors: 5,
      availableSizes: 4,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:0,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:0,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:1,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:2,
        discount: "30%SAVE",
      isFavorite: true,
      imageUrl: "https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
      altText: "Polo Shirt",
      priceBeforeDiscount: "5kd",
      priceAfterDiscount: "3.5kd",
      productName: "Men's Polo Shirt",
      availableColors: 3,
      availableSizes: 5,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:0,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:0,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:3,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:3,
        discount: "50%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
      altText: "Women's Blouse",
      priceBeforeDiscount: "6kd",
      priceAfterDiscount: "3kd",
      productName: "Women's Blouse",
      availableColors: 4,
      availableSizes: 3,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:0,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:0,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:4,
        discount: "20%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
      altText: "Hoodie",
      priceBeforeDiscount: "8kd",
      priceAfterDiscount: "6.5kd",
      productName: "Unisex Hoodie",
      availableColors: 6,
      availableSizes: 5,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:0,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:0,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:5,
        discount: "35%SAVE",
      isFavorite: true,
      imageUrl: "https://png.pngtree.com/png-vector/20230831/ourmid/pngtree-man-in-white-t-shirt-on-isolated-background-png-image_9197974.png",
      altText: "Jeans",
      priceBeforeDiscount: "10kd",
      priceAfterDiscount: "6.5kd",
      productName: "Slim Fit Jeans",
      availableColors: 2,
      availableSizes: 4,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:0,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:0,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:6,
        discount: "45%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
      altText: "Skirt",
      priceBeforeDiscount: "7kd",
      priceAfterDiscount: "3.85kd",
      productName: "Women's Skirt",
      availableColors: 4,
      availableSizes: 3,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:0,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:0,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:0,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:7,
        discount: "25%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
      altText: "Cap",
      priceBeforeDiscount: "2kd",
      priceAfterDiscount: "1.5kd",
      productName: "Sports Cap",
      availableColors: 3,
      availableSizes: 1,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
      },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:8,
        discount: "10%SAVE",
      isFavorite: true,
      imageUrl: "https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
      altText: "Jacket",
      priceBeforeDiscount: "12kd",
      priceAfterDiscount: "10.8kd",
      productName: "Leather Jacket",
      availableColors: 3,
      availableSizes: 4,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
      },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
          size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:9,
        discount: "60%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
      altText: "Sneakers",
      priceBeforeDiscount: "15kd",
      priceAfterDiscount: "6kd",
      productName: "Running Sneakers",
      availableColors: 4,
      availableSizes: 6,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
        },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:10,
        discount: "55%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-clipart/20240425/ourmid/pngtree-t-shirt-png-image_12311817.png",
      altText: "Socks",
      priceBeforeDiscount: "1.5kd",
      priceAfterDiscount: "0.67kd",
      productName: "Cotton Socks",
      availableColors: 5,
      availableSizes: 3,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
        },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:11,
        discount: "70%SAVE",
      isFavorite: true,
      imageUrl: "https://png.pngtree.com/png-vector/20240203/ourmid/pngtree-a-blue-t-shirt-with-cake-white-background-copy-png-image_11677587.png",
      altText: "Sweater",
      priceBeforeDiscount: "20kd",
      priceAfterDiscount: "6kd",
      productName: "Wool Sweater",
      availableColors: 5,
      availableSizes: 5,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
        },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:12,
        discount: "15%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-vector/20240510/ourmid/pngtree-red-t-shirt-mockup-png-image_12434254.png",
      altText: "Dress",
      priceBeforeDiscount: "9kd",
      priceAfterDiscount: "7.65kd",
      productName: "Evening Dress",
      availableColors: 4,
      availableSizes: 5,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
        },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:13,
        discount: "50%SAVE",
      isFavorite: true,
      imageUrl: "https://png.pngtree.com/png-vector/20240818/ourmid/pngtree-d-fashion-forward-blue-leather-jacket-for-trendsetters-on-transparent-background-png-image_13533855.png",
      altText: "Hat",
      priceBeforeDiscount: "5kd",
      priceAfterDiscount: "2.5kd",
      productName: "Sun Hat",
      availableColors: 2,
      availableSizes: 1,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
        },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:14,
        discount: "33%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-vector/20240806/ourmid/pngtree-winter-pu-leather-jackets-men-fleece-png-image_13117123.png",
      altText: "Shoes",
      priceBeforeDiscount: "18kd",
      priceAfterDiscount: "12kd",
      productName: "Leather Shoes",
      availableColors: 3,
      availableSizes: 4,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
        },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:15,
        discount: "80%SAVE",
      isFavorite: false,
      imageUrl: "https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
      altText: "Sandals",
      priceBeforeDiscount: "25kd",
      priceAfterDiscount: "5kd",
      productName: "Beach Sandals",
      availableColors: 4,
      availableSizes: 6,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
        },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    },
    {
      id:16,
        discount: "90%SAVE",
      isFavorite: true,
      imageUrl: "https://png.pngtree.com/png-clipart/20220710/ourmid/pngtree-jacket-illustration-png-image_5837079.png",
      altText: "Coat",
      priceBeforeDiscount: "30kd",
      priceAfterDiscount: "3kd",
      productName: "Winter Coat",
      availableColors: 5,
      availableSizes: 5,
      productColor:[
        { colorId:1,
          colorName:"green",
          colorImg:"https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-pink-t-shirt-png-image_10092008.png",
          colorOfQuentity:1,
          size:{}
        },
        {colorId:2,
        colorName:"red",
        colorImg:"https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-black-t-shirt-mockup-realistic-t-shirt-png-image_11645793.png",
        colorOfQuentity:3,
        size:{}
        },
        {colorId:3,
        colorName:"blue",
        colorImg:"https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-isolated-blank-t-shirt-front-png-image_10189369.png",
        colorOfQuentity:2,
        size:{}
      },
        {colorId:4,
          colorName:"black",
          colorImg:"https://png.pngtree.com/png-vector/20240124/ourmid/pngtree-yellow-t-shirt-png-png-image_11478589.png",
          colorOfQuentity:5,
          size:{}
        },
      ],
      TotalQuentity:0,
      TotalPrice:0,
      currentIndex:0,
      size:["S","M","X","XL","XXL","XXXL"],
    }
  ];
  